source 'https://rubygems.org'

gem 'rails', '~> 5.0.4'
gem 'sqlite3'
gem 'puma', '~> 3.0'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end

group :development do
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'pry'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'money-rails', '~> 1'
gem 'money-uphold-bank'

gem 'active_model_serializers', '~> 0.10.0'
gem 'groupdate'

gem 'rack-cors'
